- apt_repository:
    repo: deb https://packages.grafana.com/enterprise/deb stable main
    state: present
    filename: grafana

- name: "Install required packages"
  apt:
   pkg:
   - nginx
   - python
   - python-pip
   - python-setuptools
   - python3
   - python3-pip
   - python3-setuptools
   - prometheus
   - grafana

- name: "Add prometheus TLS certificate"
  template:
    src: "../../secrets/prometheus.fyc.lan.pem"
    dest: "/etc/ssl/certs"
    owner: "root"
    group: "root"
    mode: 0400

- name: "Add nginx prometheus virtualhost"
  template:
    src: "templates/prometheus.j2"
    dest: "/etc/nginx/sites-available/prometheus"
    owner: "root"
    group: "root"
    mode: 0644

- file:
    path: /etc/nginx/sites-available/prometheus
    owner: root
    group: root
    mode: 0644

- file:
    src: /etc/nginx/sites-available/prometheus
    dest: /etc/nginx/sites-enabled/prometheus
    owner: root
    group: root
    state: link

- name: "Add grafana TLS certificate"
  template:
    src: "../../secrets/grafana.fyc.lan.pem"
    dest: "/etc/ssl/certs"
    owner: "root"
    group: "root"
    mode: 0400

- name: "Add nginx grafana virtualhost"
  template:
    src: "templates/grafana.j2"
    dest: "/etc/nginx/sites-available/grafana"
    owner: "root"
    group: "root"
    mode: 0644

- file:
    path: /etc/nginx/sites-available/grafana
    owner: root
    group: root
    mode: 0644

- file:
    src: /etc/nginx/sites-available/grafana
    dest: /etc/nginx/sites-enabled/grafana
    owner: root
    group: root
    state: link

- name: Restart nginx
  service: name=nginx state=restarted enabled=yes

- name: Reload systemd
  systemd: daemon_reload=yes

- name: Start grafana
  systemd: name=grafana-server state=started enabled=yes
